### PR TITLE
Update Update-FslogixClient.ps1

### PR DESCRIPTION
**Pull request by jonwbstr**
Clean up installer files after successful update.

### CODE REVIEW

**Comment by jonwbstr** [comment]
I added a comment to the blog post yesterday, updated the script and sharing my changes.
https://blog.raindrops.dev/2022/09/18/auto-update-fslogix-client-on-azure-virtual-desktop-vms/

**Review by sergiopadure — APPROVED** [review]

**Review by sergiopadure — CHANGES_REQUESTED** [review]
This is mostly a preference of the end user though, perhaps it would be better to implement a call parameter with a default so the end user can adapt the verbose preferences and logs location

**Comment by sergiopadure** [comment]
Hi @jonwbstr . Thank you for your pull request! As indicated in the change, the first is good and I'll be glad to integrate it, but the second part is mostly a preference for the end user and I'd prefer it to be treated as such, especially the verbose output on first run for somebody not necessarily being comfortable with it.

**Comment by sergiopadure** [comment]
Hi, implemented both parameters for calling the script without verbose logging (and for defining working directory and logs location) and code to cleanup the installers if the installation is successful in v0.2. Thank you for your contribution!

**Pull request closed without merging**
